minhearts: 1
maxhearts: 15
startinghearts: 5
defaultheartchange: 1
heartpenaltycooldown: 3
transmuteitemdamage: 15
netherlevelrequired: 7

notadmin_message: 'Only admins can use this command.'
player_joined_message: 'Welcome! You have 3 minutes of immunity but once the time is up you will lose a heart when you die. When the "Bad Luck" status effect is gone you will lose hearts upon death again.'
maxhealth_invalidargs_message: 'Invalid command arguments. The command should look like: maxhealth <player> <number_of_hearts>'
maxhealthall_invalidargs_message: 'Invalid command arguments. The command should look like: maxhealthall <number_of_hearts>'
maxhealth_invalidhearts_message: 'You cannot set a player to have that amount of hearts'

treasure_transmutables: [
  {
    material: COPPER_BLOCK,
    quality: 5
  },
  {
    material: GOLD_BLOCK,
    quality: 4
  }
]

heart_transmutables: [
  {
    displayName: 'Block of Coal',
    material: COAL_BLOCK,
    levelRequired: 1,
    heartsGained: 1
  },
  {
    displayName: 'Block of Copper',
    material: COPPER_BLOCK,
    levelRequired: 2,
    heartsGained: 1
  },
  {
    displayName: 'Block of Copper',
    material: EXPOSED_COPPER,
    levelRequired: 2,
    heartsGained: 1
  },
  {
    displayName: 'Block of Copper',
    material: WEATHERED_COPPER,
    levelRequired: 2,
    heartsGained: 1
  },
  {
    displayName: 'Block of Copper',
    material: OXIDIZED_COPPER,
    levelRequired: 2,
    heartsGained: 1
  },
  {
    displayName: 'Block of Iron',
    material: IRON_BLOCK,
    levelRequired: 3,
    heartsGained: 1
  },
  {
    displayName: 'Block of Gold',
    material: GOLD_BLOCK,
    levelRequired: 4,
    heartsGained: 1
  },
  {
    displayName: 'Block of Lapis Lazuli',
    material: LAPIS_BLOCK,
    levelRequired: 5,
    heartsGained: 1
  },
  {
    displayName: 'Block of Diamond',
    material: DIAMOND_BLOCK,
    levelRequired: 6,
    heartsGained: 1
  },
  {
    displayName: 'Lodestone',
    material: LODESTONE,
    levelRequired: 7,
    heartsGained: 1
  },
  {
    displayName: 'Shulker Box',
    material: SHULKER_BOX,
    levelRequired: 8,
    heartsGained: 1
  },
  {
    displayName: 'Beacon',
    material: BEACON,
    levelRequired: 9,
    heartsGained: 1
  }
]